import { PrismaClient, Difficulty } from '@prisma/client'
import bcrypt from 'bcryptjs'

const prisma = new PrismaClient()

const patterns = [
  {
    slug: 'sliding-window', name: 'Sliding Window', description: 'Efficiently process subarrays/substrings by maintaining a window that slides over data.', difficulty: Difficulty.MEDIUM, order: 1, icon: '⊡', color: '#6366f1', timeComplexity: 'O(n)', spaceComplexity: 'O(1)',
    conceptExplanation: `# Sliding Window\n\nMaintain a window over data to avoid redundant recomputation. Instead of nested loops O(n²), slide a window in O(n).\n\n## Types\n- **Fixed size**: window size k is constant\n- **Variable size**: window expands/shrinks based on condition`,
    visualIntuition: '```\n[a, b, c, d, e]\n [--win--]\n    [--win--]\n```\nNew element enters right, old exits left.',
    stepByStep: '1. Initialize left=0, right=0\n2. Expand window by moving right\n3. Check validity\n4. Shrink from left if invalid\n5. Track optimal answer',
    templateCode: { java: `public int slidingWindow(int[] arr, int k) {\n    int sum = 0, max = 0;\n    for (int i = 0; i < k; i++) sum += arr[i];\n    max = sum;\n    for (int i = k; i < arr.length; i++) {\n        sum += arr[i] - arr[i-k];\n        max = Math.max(max, sum);\n    }\n    return max;\n}`, python: `def sliding_window(arr, k):\n    window_sum = sum(arr[:k])\n    max_sum = window_sum\n    for i in range(k, len(arr)):\n        window_sum += arr[i] - arr[i-k]\n        max_sum = max(max_sum, window_sum)\n    return max_sum`, cpp: `int slidingWindow(vector<int>& arr, int k) {\n    int sum = 0, maxSum = 0;\n    for (int i = 0; i < k; i++) sum += arr[i];\n    maxSum = sum;\n    for (int i = k; i < arr.size(); i++) {\n        sum += arr[i] - arr[i-k];\n        maxSum = max(maxSum, sum);\n    }\n    return maxSum;\n}` },
    commonMistakes: '1. Off-by-one errors\n2. Not handling k > array length\n3. Wrong shrink condition',
    interviewInsights: '- First identify: fixed or variable window?\n- Mention O(n) vs O(n²) improvement\n- Handle edge cases: empty array, k=0',
  },
  {
    slug: 'two-pointers', name: 'Two Pointers', description: 'Use two indices traversing data from different positions to solve problems in O(n).', difficulty: Difficulty.EASY, order: 2, icon: '⇄', color: '#10b981', timeComplexity: 'O(n)', spaceComplexity: 'O(1)',
    conceptExplanation: `# Two Pointers\n\nUse two pointers traversing data simultaneously. Eliminates nested loops.\n\n## Variants\n1. Opposite ends (sorted array)\n2. Same direction (fast/slow)\n3. Separate arrays`,
    visualIntuition: '```\n[1,2,3,4,5]\n L       R  sum<target → L++\n   L     R  sum>target → R--\n```',
    stepByStep: '1. Sort if needed\n2. Set left=0, right=n-1\n3. While left < right:\n   - Check condition\n   - Move appropriate pointer',
    templateCode: { java: `public int[] twoSum(int[] arr, int target) {\n    int l = 0, r = arr.length - 1;\n    while (l < r) {\n        int sum = arr[l] + arr[r];\n        if (sum == target) return new int[]{l, r};\n        else if (sum < target) l++;\n        else r--;\n    }\n    return new int[]{-1, -1};\n}`, python: `def two_sum(arr, target):\n    l, r = 0, len(arr) - 1\n    while l < r:\n        s = arr[l] + arr[r]\n        if s == target: return [l, r]\n        elif s < target: l += 1\n        else: r -= 1\n    return [-1, -1]`, cpp: `vector<int> twoSum(vector<int>& arr, int target) {\n    int l = 0, r = arr.size()-1;\n    while (l < r) {\n        int s = arr[l]+arr[r];\n        if (s==target) return {l,r};\n        else if (s<target) l++;\n        else r--;\n    }\n    return {-1,-1};\n}` },
    commonMistakes: '1. Not sorting first\n2. Moving both pointers at once\n3. Wrong boundary: left<=right vs left<right',
    interviewInsights: '- Confirm if array is sorted\n- O(n) time, O(1) space\n- Works for pairs, triplets (3Sum)',
  },
  {
    slug: 'binary-search', name: 'Binary Search', description: 'Halve the search space each step. O(log n) search on sorted data or answer space.', difficulty: Difficulty.MEDIUM, order: 3, icon: '⌖', color: '#f59e0b', timeComplexity: 'O(log n)', spaceComplexity: 'O(1)',
    conceptExplanation: `# Binary Search\n\nCut search space in half each iteration.\n\n## Variants\n1. Classic: find exact target\n2. Left bound: first occurrence\n3. Right bound: last occurrence\n4. On answer: binary search on result space`,
    visualIntuition: '```\n[-1,0,3,5,9,12], target=9\n  L     M      R  → M<target, L=M+1\n          L  M  R  → found!\n```',
    stepByStep: '1. left=0, right=n-1\n2. mid = left + (right-left)/2\n3. If arr[mid]==target: found\n4. If arr[mid]<target: left=mid+1\n5. Else: right=mid-1',
    templateCode: { java: `public int search(int[] arr, int target) {\n    int l = 0, r = arr.length - 1;\n    while (l <= r) {\n        int mid = l + (r - l) / 2;\n        if (arr[mid] == target) return mid;\n        else if (arr[mid] < target) l = mid + 1;\n        else r = mid - 1;\n    }\n    return -1;\n}`, python: `def search(arr, target):\n    l, r = 0, len(arr)-1\n    while l <= r:\n        mid = l + (r-l)//2\n        if arr[mid] == target: return mid\n        elif arr[mid] < target: l = mid+1\n        else: r = mid-1\n    return -1`, cpp: `int search(vector<int>& arr, int target) {\n    int l=0, r=arr.size()-1;\n    while (l<=r) {\n        int mid=l+(r-l)/2;\n        if (arr[mid]==target) return mid;\n        else if (arr[mid]<target) l=mid+1;\n        else r=mid-1;\n    }\n    return -1;\n}` },
    commonMistakes: '1. Overflow: use mid=l+(r-l)/2 NOT (l+r)/2\n2. Infinite loop from wrong pointer update\n3. Off-by-one: <= vs <',
    interviewInsights: '- "Search" + sorted → binary search\n- "Min/max possible" → binary search on answer\n- Always define your invariant',
  },
  {
    slug: 'dfs', name: 'Depth-First Search', description: 'Explore as deep as possible before backtracking. Foundation of tree traversal and backtracking.', difficulty: Difficulty.MEDIUM, order: 4, icon: '↯', color: '#8b5cf6', timeComplexity: 'O(V+E)', spaceComplexity: 'O(H)',
    conceptExplanation: `# DFS\n\nExplore each path completely before trying another.\n\n## Tree Orders\n- Preorder: Root→Left→Right\n- Inorder: Left→Root→Right (sorted for BST)\n- Postorder: Left→Right→Root\n\n## Graph DFS\nRequires visited set to prevent cycles.`,
    visualIntuition: '```\n    1\n   / \\\n  2   3\n / \\\n4   5\nPreorder: 1→2→4→5→3\n```',
    stepByStep: '1. Base case: null/visited → return\n2. Mark visited\n3. Process node\n4. Recurse on children\n5. Backtrack (undo state)',
    templateCode: { java: `// Tree DFS\nvoid dfs(TreeNode root) {\n    if (root == null) return;\n    process(root.val); // preorder\n    dfs(root.left);\n    dfs(root.right);\n}\n\n// Graph DFS\nvoid dfs(int node, List<List<Integer>> adj, boolean[] vis) {\n    vis[node] = true;\n    for (int nb : adj.get(node))\n        if (!vis[nb]) dfs(nb, adj, vis);\n}`, python: `def dfs(root):\n    if not root: return\n    print(root.val)  # preorder\n    dfs(root.left)\n    dfs(root.right)\n\ndef graph_dfs(node, adj, visited):\n    visited.add(node)\n    for nb in adj[node]:\n        if nb not in visited:\n            graph_dfs(nb, adj, visited)`, cpp: `void dfs(TreeNode* root) {\n    if (!root) return;\n    cout << root->val;\n    dfs(root->left);\n    dfs(root->right);\n}` },
    commonMistakes: '1. No visited set in graph DFS → infinite loop\n2. Wrong base case\n3. Not restoring state in backtracking',
    interviewInsights: '- DFS for: paths, cycles, topological sort\n- Large depth → use iterative + stack\n- Backtracking: always restore state',
  },
  {
    slug: 'bfs', name: 'Breadth-First Search', description: 'Explore level by level. Guarantees shortest path in unweighted graphs.', difficulty: Difficulty.MEDIUM, order: 5, icon: '≋', color: '#06b6d4', timeComplexity: 'O(V+E)', spaceComplexity: 'O(W)',
    conceptExplanation: `# BFS\n\nExplore all nodes at current depth before next level.\n\n## When to Use\n- Shortest path (unweighted)\n- Level-order traversal\n- Nodes within k steps\n- Word ladder problems`,
    visualIntuition: '```\nLevel 0:    1\nLevel 1:  2   3\nLevel 2: 4 5   6\nQueue: [1]→[2,3]→[4,5,6]\n```',
    stepByStep: '1. Add start to queue, mark visited\n2. While queue not empty:\n   - Snapshot size (for levels)\n   - Process all at current level\n   - Add unvisited neighbors',
    templateCode: { java: `List<List<Integer>> levelOrder(TreeNode root) {\n    List<List<Integer>> res = new ArrayList<>();\n    if (root==null) return res;\n    Queue<TreeNode> q = new LinkedList<>();\n    q.offer(root);\n    while (!q.isEmpty()) {\n        int size = q.size();\n        List<Integer> level = new ArrayList<>();\n        for (int i=0;i<size;i++) {\n            TreeNode n = q.poll();\n            level.add(n.val);\n            if (n.left!=null) q.offer(n.left);\n            if (n.right!=null) q.offer(n.right);\n        }\n        res.add(level);\n    }\n    return res;\n}`, python: `from collections import deque\ndef level_order(root):\n    if not root: return []\n    result, queue = [], deque([root])\n    while queue:\n        level = []\n        for _ in range(len(queue)):\n            node = queue.popleft()\n            level.append(node.val)\n            if node.left: queue.append(node.left)\n            if node.right: queue.append(node.right)\n        result.append(level)\n    return result`, cpp: `vector<vector<int>> levelOrder(TreeNode* root) {\n    vector<vector<int>> res;\n    if (!root) return res;\n    queue<TreeNode*> q;\n    q.push(root);\n    while (!q.empty()) {\n        int sz=q.size(); vector<int> lv;\n        for (int i=0;i<sz;i++) {\n            auto n=q.front();q.pop();\n            lv.push_back(n->val);\n            if (n->left) q.push(n->left);\n            if (n->right) q.push(n->right);\n        }\n        res.push_back(lv);\n    }\n    return res;\n}` },
    commonMistakes: '1. Mark visited BEFORE adding to queue (not after dequeue)\n2. Not snapshotting level size\n3. Using BFS when DFS is better',
    interviewInsights: '- BFS = shortest path in unweighted graphs\n- Weighted → Dijkstra\n- Multi-source BFS: start with multiple nodes',
  },
  {
    slug: 'dynamic-programming', name: 'Dynamic Programming', description: 'Solve overlapping subproblems by storing results. Convert exponential to polynomial time.', difficulty: Difficulty.HARD, order: 6, icon: '⬡', color: '#ef4444', timeComplexity: 'O(n²) typical', spaceComplexity: 'O(n) to O(n²)',
    conceptExplanation: `# Dynamic Programming\n\nOptimization via overlapping subproblems + optimal substructure.\n\n## Approaches\n- **Top-Down**: Recursive + memoization\n- **Bottom-Up**: Iterative tabulation\n\n## Framework\n1. Define state\n2. Base case\n3. Transition\n4. Answer`,
    visualIntuition: '```\nfib(5) without memo: O(2^n)\nfib(5) with memo:\n  fib(4)     fib(3)✓cached\n  fib(3)✓  fib(2)✓\n```',
    stepByStep: '1. Define dp[i] meaning\n2. Set base cases\n3. Write recurrence: dp[i]=f(dp[i-1]...)\n4. Return dp[n]',
    templateCode: { java: `// Memoization\nMap<Integer,Long> memo = new HashMap<>();\nlong fib(int n) {\n    if (n<=1) return n;\n    if (memo.containsKey(n)) return memo.get(n);\n    long res = fib(n-1)+fib(n-2);\n    memo.put(n,res);\n    return res;\n}\n\n// Tabulation\nint coinChange(int[] coins, int amount) {\n    int[] dp = new int[amount+1];\n    Arrays.fill(dp, amount+1);\n    dp[0]=0;\n    for (int i=1;i<=amount;i++)\n        for (int c:coins)\n            if (c<=i) dp[i]=Math.min(dp[i],dp[i-c]+1);\n    return dp[amount]>amount?-1:dp[amount];\n}`, python: `from functools import lru_cache\n\n@lru_cache(None)\ndef fib(n):\n    if n <= 1: return n\n    return fib(n-1) + fib(n-2)\n\ndef coin_change(coins, amount):\n    dp = [float('inf')] * (amount+1)\n    dp[0] = 0\n    for i in range(1, amount+1):\n        for c in coins:\n            if c <= i:\n                dp[i] = min(dp[i], dp[i-c]+1)\n    return dp[amount] if dp[amount] != float('inf') else -1`, cpp: `// Tabulation\nint coinChange(vector<int>& coins, int amount) {\n    vector<int> dp(amount+1, amount+1);\n    dp[0]=0;\n    for (int i=1;i<=amount;i++)\n        for (int c:coins)\n            if (c<=i) dp[i]=min(dp[i],dp[i-c]+1);\n    return dp[amount]>amount?-1:dp[amount];\n}` },
    commonMistakes: '1. Wrong state definition\n2. Missing base cases\n3. Wrong transition order\n4. Not space-optimizing (2D→1D often possible)',
    interviewInsights: '- Start with brute force → add memo\n- Identify "choices" at each step\n- Classics: Knapsack, LCS, Edit Distance, Coin Change',
  },
  {
    slug: 'backtracking', name: 'Backtracking', description: 'Build solutions incrementally, abandon paths that cannot lead to valid solutions.', difficulty: Difficulty.HARD, order: 7, icon: '↩', color: '#f97316', timeComplexity: 'O(n!)', spaceComplexity: 'O(n)',
    conceptExplanation: `# Backtracking\n\nTemplate:\n\`\`\`\nbacktrack(state):\n    if complete: add to results; return\n    for choice in choices:\n        if valid(choice):\n            make(choice)\n            backtrack(state)\n            undo(choice)  ← KEY\n\`\`\``,
    visualIntuition: '```\nSubsets [1,2,3]:\n        []\n    [1]  [2]  [3]\n  [1,2][1,3] [2,3]\n [1,2,3]\n```',
    stepByStep: '1. Define state\n2. Base case (complete solution)\n3. Loop through choices\n4. Prune invalid\n5. Choose → recurse → unchoose',
    templateCode: { java: `void backtrack(List<List<Integer>> res, List<Integer> curr, int[] nums, int start) {\n    res.add(new ArrayList<>(curr));\n    for (int i=start;i<nums.length;i++) {\n        curr.add(nums[i]);       // choose\n        backtrack(res,curr,nums,i+1); // explore\n        curr.remove(curr.size()-1);   // unchoose\n    }\n}`, python: `def backtrack(start, current, nums, result):\n    result.append(current[:])\n    for i in range(start, len(nums)):\n        current.append(nums[i])    # choose\n        backtrack(i+1, current, nums, result)  # explore\n        current.pop()              # unchoose`, cpp: `void backtrack(vector<vector<int>>& res, vector<int>& curr, vector<int>& nums, int start) {\n    res.push_back(curr);\n    for (int i=start;i<nums.size();i++) {\n        curr.push_back(nums[i]);\n        backtrack(res,curr,nums,i+1);\n        curr.pop_back();\n    }\n}` },
    commonMistakes: '1. Forgetting unchoose step\n2. Adding reference not copy to results\n3. Not pruning (TLE)\n4. Duplicates: sort first, skip same elements',
    interviewInsights: '- Classics: Subsets, Permutations, N-Queens, Sudoku\n- State + Choices + Constraints\n- Pruning is the key optimization',
  },
  {
    slug: 'greedy', name: 'Greedy', description: 'Make locally optimal choices at each step. Works when greedy choice property holds.', difficulty: Difficulty.MEDIUM, order: 8, icon: '◈', color: '#84cc16', timeComplexity: 'O(n log n)', spaceComplexity: 'O(1)',
    conceptExplanation: `# Greedy\n\nMake the best choice at each step without reconsidering.\n\n## Works When\n- Greedy choice property: local optimal → global optimal\n- Optimal substructure\n\n## Common Problems\n- Interval scheduling\n- Huffman coding\n- Activity selection`,
    visualIntuition: '```\nActivity Selection (sort by end time):\n[1-4] [3-5] [5-7] [6-10] [8-11]\nPick [1-4] → next start≥4\nPick [5-7] → next start≥7\nPick [8-11] → done! Max=3\n```',
    stepByStep: '1. Identify greedy criterion\n2. Sort by that criterion\n3. Iterate and greedily choose\n4. Update state',
    templateCode: { java: `// Non-overlapping intervals\nint eraseOverlapIntervals(int[][] intervals) {\n    Arrays.sort(intervals, (a,b)->a[1]-b[1]);\n    int count=0, end=Integer.MIN_VALUE;\n    for (int[] iv:intervals) {\n        if (iv[0]>=end) end=iv[1];\n        else count++;\n    }\n    return count;\n}`, python: `def erase_overlap_intervals(intervals):\n    intervals.sort(key=lambda x: x[1])\n    count, end = 0, float('-inf')\n    for start, finish in intervals:\n        if start >= end: end = finish\n        else: count += 1\n    return count`, cpp: `int eraseOverlapIntervals(vector<vector<int>>& iv) {\n    sort(iv.begin(),iv.end(),[](auto& a,auto& b){return a[1]<b[1];});\n    int cnt=0,end=INT_MIN;\n    for (auto& i:iv) { if (i[0]>=end) end=i[1]; else cnt++; }\n    return cnt;\n}` },
    commonMistakes: '1. Using greedy when DP is needed\n2. Wrong sort criterion\n3. Not proving correctness',
    interviewInsights: '- Interval problems → usually greedy\n- Prove with exchange argument\n- If greedy fails → try DP',
  },
  {
    slug: 'heap', name: 'Heap / Priority Queue', description: 'Efficiently access min/max element. Perfect for top-K problems and streaming data.', difficulty: Difficulty.MEDIUM, order: 9, icon: '△', color: '#ec4899', timeComplexity: 'O(n log k)', spaceComplexity: 'O(k)',
    conceptExplanation: `# Heap / Priority Queue\n\nA complete binary tree where parent ≤ children (min-heap).\n\n## Operations\n- Insert: O(log n)\n- Get min/max: O(1)\n- Remove min/max: O(log n)\n\n## Top-K Pattern\nUse min-heap of size k to find k largest elements.`,
    visualIntuition: '```\nMin-Heap:\n      1\n     / \\\n    3   2\n   / \\\n  5   4\nParent always ≤ children\n```',
    stepByStep: '1. Initialize heap\n2. Add elements\n3. If size > k, poll minimum\n4. Heap contains k largest',
    templateCode: { java: `// Top K largest\nint[] topKFrequent(int[] nums, int k) {\n    Map<Integer,Integer> freq = new HashMap<>();\n    for (int n:nums) freq.merge(n,1,Integer::sum);\n    PriorityQueue<Integer> pq = new PriorityQueue<>((a,b)->freq.get(a)-freq.get(b));\n    for (int n:freq.keySet()) {\n        pq.offer(n);\n        if (pq.size()>k) pq.poll();\n    }\n    int[] res=new int[k];\n    for (int i=k-1;i>=0;i--) res[i]=pq.poll();\n    return res;\n}`, python: `import heapq\n\ndef top_k_frequent(nums, k):\n    freq = {}\n    for n in nums: freq[n] = freq.get(n,0)+1\n    # min-heap of size k\n    heap = []\n    for num, cnt in freq.items():\n        heapq.heappush(heap, (cnt, num))\n        if len(heap) > k: heapq.heappop(heap)\n    return [h[1] for h in heap]`, cpp: `vector<int> topKFrequent(vector<int>& nums, int k) {\n    map<int,int> freq;\n    for (int n:nums) freq[n]++;\n    priority_queue<pair<int,int>, vector<pair<int,int>>, greater<>> pq;\n    for (auto& [n,f]:freq) {\n        pq.push({f,n});\n        if (pq.size()>k) pq.pop();\n    }\n    vector<int> res;\n    while (!pq.empty()) { res.push_back(pq.top().second); pq.pop(); }\n    return res;\n}` },
    commonMistakes: '1. Using max-heap when min-heap needed\n2. Not maintaining heap size for top-K\n3. Forgetting heap is not sorted',
    interviewInsights: '- "K largest/smallest/frequent" → heap\n- Merge K sorted lists → heap\n- Median of stream → two heaps',
  },
  {
    slug: 'linked-list', name: 'Linked List', description: 'Pointer manipulation techniques for singly and doubly linked lists.', difficulty: Difficulty.MEDIUM, order: 10, icon: '⟷', color: '#14b8a6', timeComplexity: 'O(n)', spaceComplexity: 'O(1)',
    conceptExplanation: `# Linked List Techniques\n\n## Key Patterns\n1. **Dummy node**: Simplify edge cases\n2. **Fast/slow pointers**: Cycle detection, middle\n3. **Reverse**: Iterative with prev/curr/next\n4. **Two pointers**: Nth from end`,
    visualIntuition: '```\nReverse: 1→2→3→null\nprev=null, curr=1\nStep: next=2, 1→null, prev=1, curr=2\nStep: next=3, 2→1, prev=2, curr=3\nResult: 3→2→1→null\n```',
    stepByStep: '1. Use dummy node for head manipulation\n2. Save next before overwriting\n3. Update pointers carefully\n4. Return dummy.next',
    templateCode: { java: `// Reverse Linked List\nListNode reverse(ListNode head) {\n    ListNode prev=null, curr=head;\n    while (curr!=null) {\n        ListNode next=curr.next;\n        curr.next=prev;\n        prev=curr; curr=next;\n    }\n    return prev;\n}\n// Middle of list\nListNode middle(ListNode head) {\n    ListNode s=head, f=head;\n    while (f!=null && f.next!=null) {\n        s=s.next; f=f.next.next;\n    }\n    return s;\n}`, python: `def reverse(head):\n    prev, curr = None, head\n    while curr:\n        nxt = curr.next\n        curr.next = prev\n        prev, curr = curr, nxt\n    return prev\n\ndef middle(head):\n    slow = fast = head\n    while fast and fast.next:\n        slow = slow.next\n        fast = fast.next.next\n    return slow`, cpp: `ListNode* reverse(ListNode* head) {\n    ListNode *prev=nullptr, *curr=head;\n    while (curr) {\n        auto nxt=curr->next;\n        curr->next=prev;\n        prev=curr; curr=nxt;\n    }\n    return prev;\n}` },
    commonMistakes: '1. Losing reference to next before overwriting\n2. Not using dummy node for head changes\n3. Off-by-one in fast/slow pointers',
    interviewInsights: '- Draw the pointer changes on paper\n- Dummy node prevents null checks\n- Most problems solved with prev/curr/next triple',
  },
]

const problems = [
  // SLIDING WINDOW
  { slug: 'max-sum-subarray-k', title: 'Maximum Sum Subarray of Size K', difficulty: Difficulty.EASY, patternSlug: 'sliding-window', order: 1, companies: ['Amazon','Google'], tags: ['Array','Sliding Window'], description: 'Given array of integers and k, find maximum sum of contiguous subarray of size k.\n\n**Example:**\nInput: arr=[2,1,5,1,3,2], k=3\nOutput: 9\nExplanation: [5,1,3] has sum 9', examples: [{input:'arr=[2,1,5,1,3,2], k=3',output:'9',explanation:'Subarray [5,1,3]'},{input:'arr=[2,3,4,1,5], k=2',output:'7',explanation:'Subarray [3,4]'}], constraints:['1<=k<=arr.length<=1e5','1<=arr[i]<=1e4'], hints:['Build first window, then slide','Add new element, remove leftmost'], editorialText:'Fixed sliding window of size k.', editorialCode:{java:`public int maxSum(int[] arr, int k) {\n    int sum=0,max=0;\n    for(int i=0;i<k;i++) sum+=arr[i];\n    max=sum;\n    for(int i=k;i<arr.length;i++){\n        sum+=arr[i]-arr[i-k];\n        max=Math.max(max,sum);\n    }\n    return max;\n}`,python:`def max_sum(arr,k):\n    s=sum(arr[:k]); mx=s\n    for i in range(k,len(arr)):\n        s+=arr[i]-arr[i-k]; mx=max(mx,s)\n    return mx`,cpp:`int maxSum(vector<int>& a,int k){\n    int s=0,mx=0;\n    for(int i=0;i<k;i++) s+=a[i]; mx=s;\n    for(int i=k;i<a.size();i++){s+=a[i]-a[i-k];mx=max(mx,s);}\n    return mx;\n}`} },
  { slug: 'longest-substring-no-repeat', title: 'Longest Substring Without Repeating Characters', difficulty: Difficulty.MEDIUM, patternSlug: 'sliding-window', order: 2, companies: ['Amazon','Google','Facebook','Microsoft'], tags: ['String','Hash Map'], description: 'Given string s, find length of longest substring without repeating characters.\n\n**Example:**\nInput: s="abcabcbb"\nOutput: 3\nExplanation: "abc" has length 3', examples: [{input:'s="abcabcbb"',output:'3'},{input:'s="bbbbb"',output:'1'},{input:'s="pwwkew"',output:'3'}], constraints:['0<=s.length<=5e4'], hints:['Variable window with hash map','Move left past last occurrence of repeat'], editorialText:'Variable window. Track last index of each char.', editorialCode:{java:`public int lengthOfLongest(String s) {\n    Map<Character,Integer> map=new HashMap<>();\n    int max=0,l=0;\n    for(int r=0;r<s.length();r++){\n        char c=s.charAt(r);\n        if(map.containsKey(c)) l=Math.max(l,map.get(c)+1);\n        map.put(c,r);\n        max=Math.max(max,r-l+1);\n    }\n    return max;\n}`,python:`def length_of_longest(s):\n    mp={};l=mx=0\n    for r,c in enumerate(s):\n        if c in mp: l=max(l,mp[c]+1)\n        mp[c]=r; mx=max(mx,r-l+1)\n    return mx`,cpp:`int lengthOfLongest(string s){\n    unordered_map<char,int> mp;\n    int mx=0,l=0;\n    for(int r=0;r<s.size();r++){\n        if(mp.count(s[r])) l=max(l,mp[s[r]]+1);\n        mp[s[r]]=r; mx=max(mx,r-l+1);\n    }\n    return mx;\n}`} },
  { slug: 'minimum-size-subarray-sum', title: 'Minimum Size Subarray Sum', difficulty: Difficulty.MEDIUM, patternSlug: 'sliding-window', order: 3, companies: ['Amazon','Adobe'], tags: ['Array','Sliding Window'], description: 'Given array of positive integers and target, find minimum length subarray whose sum >= target.\n\n**Example:**\nInput: target=7, nums=[2,3,1,2,4,3]\nOutput: 2\nExplanation: [4,3] has min length 2', examples: [{input:'target=7, nums=[2,3,1,2,4,3]',output:'2'},{input:'target=4, nums=[1,4,4]',output:'1'}], constraints:['1<=target<=1e9','1<=nums.length<=1e5'], hints:['Expand right, shrink left while sum>=target'], editorialText:'Variable window. Shrink from left while valid.', editorialCode:{java:`public int minSubArrayLen(int t, int[] nums) {\n    int l=0,sum=0,min=Integer.MAX_VALUE;\n    for(int r=0;r<nums.length;r++){\n        sum+=nums[r];\n        while(sum>=t){min=Math.min(min,r-l+1);sum-=nums[l++];}\n    }\n    return min==Integer.MAX_VALUE?0:min;\n}`,python:`def min_sub_len(t,nums):\n    l=s=0; mn=float('inf')\n    for r in range(len(nums)):\n        s+=nums[r]\n        while s>=t: mn=min(mn,r-l+1);s-=nums[l];l+=1\n    return 0 if mn==float('inf') else mn`,cpp:`int minSubArrayLen(int t,vector<int>& a){\n    int l=0,s=0,mn=INT_MAX;\n    for(int r=0;r<a.size();r++){\n        s+=a[r];\n        while(s>=t){mn=min(mn,r-l+1);s-=a[l++];}\n    }\n    return mn==INT_MAX?0:mn;\n}`} },
  { slug: 'fruit-into-baskets', title: 'Fruit Into Baskets', difficulty: Difficulty.MEDIUM, patternSlug: 'sliding-window', order: 4, companies: ['Google','Amazon'], tags: ['Array','Hash Map'], description: 'You have two baskets. Pick fruits from a row of trees. Each basket holds only one type. Find maximum fruits you can pick.\n\n**Example:**\nInput: fruits=[1,2,1]\nOutput: 3', examples: [{input:'fruits=[1,2,1]',output:'3'},{input:'fruits=[0,1,2,2]',output:'3'}], constraints:['1<=fruits.length<=1e5'], hints:['Max window with at most 2 distinct values','Use hash map to count'], editorialText:'Variable window with at most 2 distinct types.', editorialCode:{java:`public int totalFruit(int[] f) {\n    Map<Integer,Integer> map=new HashMap<>();\n    int l=0,max=0;\n    for(int r=0;r<f.length;r++){\n        map.merge(f[r],1,Integer::sum);\n        while(map.size()>2){int v=f[l++];map.merge(v,-1,Integer::sum);if(map.get(v)==0)map.remove(v);}\n        max=Math.max(max,r-l+1);\n    }\n    return max;\n}`,python:`def total_fruit(f):\n    from collections import defaultdict\n    cnt=defaultdict(int);l=mx=0\n    for r,v in enumerate(f):\n        cnt[v]+=1\n        while len(cnt)>2: cnt[f[l]]-=1;(cnt.pop(f[l]) if cnt[f[l]]==0 else None);l+=1\n        mx=max(mx,r-l+1)\n    return mx`,cpp:`int totalFruit(vector<int>& f){\n    unordered_map<int,int> mp;\n    int l=0,mx=0;\n    for(int r=0;r<f.size();r++){\n        mp[f[r]]++;\n        while(mp.size()>2){if(--mp[f[l]]==0)mp.erase(f[l]);l++;}\n        mx=max(mx,r-l+1);\n    }\n    return mx;\n}`} },
  // TWO POINTERS
  { slug: 'two-sum-sorted', title: 'Two Sum II - Sorted Array', difficulty: Difficulty.MEDIUM, patternSlug: 'two-pointers', order: 1, companies: ['Amazon','Bloomberg'], tags: ['Array','Two Pointers'], description: 'Given 1-indexed sorted array, find two numbers that add to target.\n\n**Example:**\nInput: numbers=[2,7,11,15], target=9\nOutput: [1,2]', examples: [{input:'numbers=[2,7,11,15], target=9',output:'[1,2]'},{input:'numbers=[2,3,4], target=6',output:'[1,3]'}], constraints:['2<=numbers.length<=3e4','Exactly one solution'], hints:['Opposite ends','Sum too small→move left, too large→move right'], editorialText:'Classic opposite-ends two pointer.', editorialCode:{java:`public int[] twoSum(int[] n,int t){\n    int l=0,r=n.length-1;\n    while(l<r){int s=n[l]+n[r];if(s==t)return new int[]{l+1,r+1};else if(s<t)l++;else r--;}\n    return new int[]{-1,-1};\n}`,python:`def two_sum(n,t):\n    l,r=0,len(n)-1\n    while l<r:\n        s=n[l]+n[r]\n        if s==t: return [l+1,r+1]\n        elif s<t: l+=1\n        else: r-=1`,cpp:`vector<int> twoSum(vector<int>& n,int t){\n    int l=0,r=n.size()-1;\n    while(l<r){int s=n[l]+n[r];if(s==t)return{l+1,r+1};else if(s<t)l++;else r--;}\n    return{-1,-1};\n}`} },
  { slug: 'three-sum', title: '3Sum', difficulty: Difficulty.MEDIUM, patternSlug: 'two-pointers', order: 2, companies: ['Facebook','Amazon','Google','Microsoft'], tags: ['Array','Two Pointers','Sorting'], description: 'Find all unique triplets that sum to zero.\n\n**Example:**\nInput: nums=[-1,0,1,2,-1,-4]\nOutput: [[-1,-1,2],[-1,0,1]]', examples: [{input:'nums=[-1,0,1,2,-1,-4]',output:'[[-1,-1,2],[-1,0,1]]'},{input:'nums=[0,1,1]',output:'[]'}], constraints:['3<=nums.length<=3000','-1e5<=nums[i]<=1e5'], hints:['Sort first','Fix one element, two-pointer for rest','Skip duplicates'], editorialText:'Sort, fix i, two-pointer for j and k. Skip duplicates.', editorialCode:{java:`public List<List<Integer>> threeSum(int[] nums){\n    Arrays.sort(nums); List<List<Integer>> res=new ArrayList<>();\n    for(int i=0;i<nums.length-2;i++){\n        if(i>0&&nums[i]==nums[i-1])continue;\n        int l=i+1,r=nums.length-1;\n        while(l<r){\n            int s=nums[i]+nums[l]+nums[r];\n            if(s==0){res.add(Arrays.asList(nums[i],nums[l],nums[r]));while(l<r&&nums[l]==nums[l+1])l++;while(l<r&&nums[r]==nums[r-1])r--;l++;r--;}\n            else if(s<0)l++; else r--;\n        }\n    }\n    return res;\n}`,python:`def three_sum(nums):\n    nums.sort(); res=[]\n    for i in range(len(nums)-2):\n        if i>0 and nums[i]==nums[i-1]: continue\n        l,r=i+1,len(nums)-1\n        while l<r:\n            s=nums[i]+nums[l]+nums[r]\n            if s==0:\n                res.append([nums[i],nums[l],nums[r]])\n                while l<r and nums[l]==nums[l+1]: l+=1\n                while l<r and nums[r]==nums[r-1]: r-=1\n                l+=1;r-=1\n            elif s<0: l+=1\n            else: r-=1\n    return res`,cpp:`vector<vector<int>> threeSum(vector<int>& n){\n    sort(n.begin(),n.end()); vector<vector<int>> res;\n    for(int i=0;i<n.size()-2;i++){\n        if(i>0&&n[i]==n[i-1])continue;\n        int l=i+1,r=n.size()-1;\n        while(l<r){\n            int s=n[i]+n[l]+n[r];\n            if(s==0){res.push_back({n[i],n[l],n[r]});while(l<r&&n[l]==n[l+1])l++;while(l<r&&n[r]==n[r-1])r--;l++;r--;}\n            else if(s<0)l++;else r--;\n        }\n    }\n    return res;\n}`} },
  { slug: 'container-with-most-water', title: 'Container With Most Water', difficulty: Difficulty.MEDIUM, patternSlug: 'two-pointers', order: 3, companies: ['Amazon','Google','Goldman Sachs'], tags: ['Array','Two Pointers','Greedy'], description: 'Find two lines that together with x-axis form container holding most water.\n\n**Example:**\nInput: height=[1,8,6,2,5,4,8,3,7]\nOutput: 49', examples: [{input:'height=[1,8,6,2,5,4,8,3,7]',output:'49'},{input:'height=[1,1]',output:'1'}], constraints:['2<=height.length<=1e5','0<=height[i]<=1e4'], hints:['Move the shorter pointer inward','Area = min(h[l],h[r]) * (r-l)'], editorialText:'Two pointers. Always move the shorter height pointer.', editorialCode:{java:`public int maxArea(int[] h){\n    int l=0,r=h.length-1,max=0;\n    while(l<r){max=Math.max(max,Math.min(h[l],h[r])*(r-l));if(h[l]<h[r])l++;else r--;}\n    return max;\n}`,python:`def max_area(h):\n    l,r,mx=0,len(h)-1,0\n    while l<r:\n        mx=max(mx,min(h[l],h[r])*(r-l))\n        if h[l]<h[r]: l+=1\n        else: r-=1\n    return mx`,cpp:`int maxArea(vector<int>& h){\n    int l=0,r=h.size()-1,mx=0;\n    while(l<r){mx=max(mx,min(h[l],h[r])*(r-l));if(h[l]<h[r])l++;else r--;}\n    return mx;\n}`} },
  // BINARY SEARCH
  { slug: 'binary-search-classic', title: 'Binary Search', difficulty: Difficulty.EASY, patternSlug: 'binary-search', order: 1, companies: ['Google','Amazon','Facebook'], tags: ['Array','Binary Search'], description: 'Search target in sorted array. Return index or -1.\n\n**Example:**\nInput: nums=[-1,0,3,5,9,12], target=9\nOutput: 4', examples: [{input:'nums=[-1,0,3,5,9,12], target=9',output:'4'},{input:'nums=[-1,0,3,5,9,12], target=2',output:'-1'}], constraints:['1<=nums.length<=1e4','All unique, sorted ascending'], hints:['mid = left + (right-left)/2 to avoid overflow'], editorialText:'Classic binary search.', editorialCode:{java:`public int search(int[] nums,int t){\n    int l=0,r=nums.length-1;\n    while(l<=r){int m=l+(r-l)/2;if(nums[m]==t)return m;else if(nums[m]<t)l=m+1;else r=m-1;}\n    return -1;\n}`,python:`def search(nums,t):\n    l,r=0,len(nums)-1\n    while l<=r:\n        m=l+(r-l)//2\n        if nums[m]==t: return m\n        elif nums[m]<t: l=m+1\n        else: r=m-1\n    return -1`,cpp:`int search(vector<int>& n,int t){\n    int l=0,r=n.size()-1;\n    while(l<=r){int m=l+(r-l)/2;if(n[m]==t)return m;else if(n[m]<t)l=m+1;else r=m-1;}\n    return -1;\n}`} },
  { slug: 'find-minimum-rotated-sorted', title: 'Find Minimum in Rotated Sorted Array', difficulty: Difficulty.MEDIUM, patternSlug: 'binary-search', order: 2, companies: ['Amazon','Microsoft','Google'], tags: ['Array','Binary Search'], description: 'Find minimum in rotated sorted array.\n\n**Example:**\nInput: nums=[3,4,5,1,2]\nOutput: 1', examples: [{input:'nums=[3,4,5,1,2]',output:'1'},{input:'nums=[4,5,6,7,0,1,2]',output:'0'}], constraints:['All unique integers'], hints:['If nums[mid]>nums[right], min is in right half','Else min is in left half including mid'], editorialText:'Binary search. Compare mid with right to determine which half.', editorialCode:{java:`public int findMin(int[] n){\n    int l=0,r=n.length-1;\n    while(l<r){int m=l+(r-l)/2;if(n[m]>n[r])l=m+1;else r=m;}\n    return n[l];\n}`,python:`def find_min(n):\n    l,r=0,len(n)-1\n    while l<r:\n        m=l+(r-l)//2\n        if n[m]>n[r]: l=m+1\n        else: r=m\n    return n[l]`,cpp:`int findMin(vector<int>& n){\n    int l=0,r=n.size()-1;\n    while(l<r){int m=l+(r-l)/2;if(n[m]>n[r])l=m+1;else r=m;}\n    return n[l];\n}`} },
  { slug: 'search-in-rotated-array', title: 'Search in Rotated Sorted Array', difficulty: Difficulty.MEDIUM, patternSlug: 'binary-search', order: 3, companies: ['Amazon','Facebook','Microsoft','Apple'], tags: ['Array','Binary Search'], description: 'Search target in rotated sorted array. Return index or -1.\n\n**Example:**\nInput: nums=[4,5,6,7,0,1,2], target=0\nOutput: 4', examples: [{input:'nums=[4,5,6,7,0,1,2], target=0',output:'4'},{input:'nums=[4,5,6,7,0,1,2], target=3',output:'-1'}], constraints:['All unique integers'], hints:['One half is always sorted','Check if target is in the sorted half'], editorialText:'Determine which half is sorted, check if target lies there.', editorialCode:{java:`public int search(int[] n,int t){\n    int l=0,r=n.length-1;\n    while(l<=r){int m=l+(r-l)/2;if(n[m]==t)return m;if(n[l]<=n[m]){if(t>=n[l]&&t<n[m])r=m-1;else l=m+1;}else{if(t>n[m]&&t<=n[r])l=m+1;else r=m-1;}}\n    return -1;\n}`,python:`def search(n,t):\n    l,r=0,len(n)-1\n    while l<=r:\n        m=l+(r-l)//2\n        if n[m]==t: return m\n        if n[l]<=n[m]:\n            if n[l]<=t<n[m]: r=m-1\n            else: l=m+1\n        else:\n            if n[m]<t<=n[r]: l=m+1\n            else: r=m-1\n    return -1`,cpp:`int search(vector<int>& n,int t){\n    int l=0,r=n.size()-1;\n    while(l<=r){int m=l+(r-l)/2;if(n[m]==t)return m;if(n[l]<=n[m]){if(t>=n[l]&&t<n[m])r=m-1;else l=m+1;}else{if(t>n[m]&&t<=n[r])l=m+1;else r=m-1;}}\n    return -1;\n}`} },
  // DFS
  { slug: 'number-of-islands', title: 'Number of Islands', difficulty: Difficulty.MEDIUM, patternSlug: 'dfs', order: 1, companies: ['Amazon','Google','Facebook','Microsoft'], tags: ['Array','DFS','BFS'], description: 'Count number of islands in a 2D grid. Island = group of connected 1s surrounded by 0s/water.\n\n**Example:**\nInput: grid=[["1","1","0"],["1","1","0"],["0","0","1"]]\nOutput: 2', examples: [{input:'grid=[["1","1","0"],["0","1","0"],["0","0","1"]]',output:'2'},{input:'grid=[["1","1","1"],["0","1","0"],["1","1","1"]]',output:'1'}], constraints:['1<=grid dimensions<=300'], hints:['DFS from each unvisited "1"','Mark visited cells as "0"'], editorialText:'DFS from each "1", mark connected cells as visited.', editorialCode:{java:`public int numIslands(char[][] g){\n    int cnt=0;\n    for(int i=0;i<g.length;i++) for(int j=0;j<g[0].length;j++) if(g[i][j]=='1'){dfs(g,i,j);cnt++;}\n    return cnt;\n}\nvoid dfs(char[][] g,int i,int j){\n    if(i<0||i>=g.length||j<0||j>=g[0].length||g[i][j]!='1')return;\n    g[i][j]='0';\n    dfs(g,i+1,j);dfs(g,i-1,j);dfs(g,i,j+1);dfs(g,i,j-1);\n}`,python:`def num_islands(grid):\n    def dfs(i,j):\n        if i<0 or i>=len(grid) or j<0 or j>=len(grid[0]) or grid[i][j]!='1': return\n        grid[i][j]='0'\n        dfs(i+1,j);dfs(i-1,j);dfs(i,j+1);dfs(i,j-1)\n    cnt=0\n    for i in range(len(grid)):\n        for j in range(len(grid[0])):\n            if grid[i][j]=='1': dfs(i,j);cnt+=1\n    return cnt`,cpp:`int numIslands(vector<vector<char>>& g){\n    int cnt=0;\n    function<void(int,int)> dfs=[&](int i,int j){\n        if(i<0||i>=g.size()||j<0||j>=g[0].size()||g[i][j]!='1')return;\n        g[i][j]='0';dfs(i+1,j);dfs(i-1,j);dfs(i,j+1);dfs(i,j-1);\n    };\n    for(int i=0;i<g.size();i++) for(int j=0;j<g[0].size();j++) if(g[i][j]=='1'){dfs(i,j);cnt++;}\n    return cnt;\n}`} },
  { slug: 'max-area-of-island', title: 'Max Area of Island', difficulty: Difficulty.MEDIUM, patternSlug: 'dfs', order: 2, companies: ['Amazon','Google'], tags: ['Array','DFS'], description: 'Find maximum area of island in a 2D grid.\n\n**Example:**\nInput: grid with multiple islands\nOutput: 6', examples: [{input:'grid=[[0,0,1,0],[0,1,1,0],[0,1,0,0]]',output:'4'}], constraints:['1<=grid dimensions<=50'], hints:['DFS returns size of island','Track max across all islands'], editorialText:'DFS returning count of connected 1s.', editorialCode:{java:`public int maxAreaOfIsland(int[][] g){\n    int max=0;\n    for(int i=0;i<g.length;i++) for(int j=0;j<g[0].length;j++) max=Math.max(max,dfs(g,i,j));\n    return max;\n}\nint dfs(int[][] g,int i,int j){\n    if(i<0||i>=g.length||j<0||j>=g[0].length||g[i][j]==0)return 0;\n    g[i][j]=0;\n    return 1+dfs(g,i+1,j)+dfs(g,i-1,j)+dfs(g,i,j+1)+dfs(g,i,j-1);\n}`,python:`def max_area(grid):\n    def dfs(i,j):\n        if i<0 or i>=len(grid) or j<0 or j>=len(grid[0]) or grid[i][j]==0: return 0\n        grid[i][j]=0\n        return 1+dfs(i+1,j)+dfs(i-1,j)+dfs(i,j+1)+dfs(i,j-1)\n    return max(dfs(i,j) for i in range(len(grid)) for j in range(len(grid[0])))`,cpp:`int maxArea(vector<vector<int>>& g){\n    int mx=0;\n    function<int(int,int)> dfs=[&](int i,int j)->int{\n        if(i<0||i>=g.size()||j<0||j>=g[0].size()||!g[i][j])return 0;\n        g[i][j]=0;\n        return 1+dfs(i+1,j)+dfs(i-1,j)+dfs(i,j+1)+dfs(i,j-1);\n    };\n    for(int i=0;i<g.size();i++) for(int j=0;j<g[0].size();j++) mx=max(mx,dfs(i,j));\n    return mx;\n}`} },
  // BFS
  { slug: 'binary-tree-level-order', title: 'Binary Tree Level Order Traversal', difficulty: Difficulty.MEDIUM, patternSlug: 'bfs', order: 1, companies: ['Amazon','Microsoft','Facebook'], tags: ['Tree','BFS'], description: 'Return level order traversal of binary tree as list of lists.\n\n**Example:**\nInput: root=[3,9,20,null,null,15,7]\nOutput: [[3],[9,20],[15,7]]', examples: [{input:'root=[3,9,20,null,null,15,7]',output:'[[3],[9,20],[15,7]]'},{input:'root=[1]',output:'[[1]]'}], constraints:['0<=nodes<=2000'], hints:['Use queue, snapshot level size before inner loop'], editorialText:'BFS with level-size snapshot.', editorialCode:{java:`public List<List<Integer>> levelOrder(TreeNode root){\n    List<List<Integer>> res=new ArrayList<>();\n    if(root==null)return res;\n    Queue<TreeNode> q=new LinkedList<>();q.offer(root);\n    while(!q.isEmpty()){int sz=q.size();List<Integer> lv=new ArrayList<>();for(int i=0;i<sz;i++){TreeNode n=q.poll();lv.add(n.val);if(n.left!=null)q.offer(n.left);if(n.right!=null)q.offer(n.right);}res.add(lv);}\n    return res;\n}`,python:`from collections import deque\ndef level_order(root):\n    if not root: return []\n    res,q=[],deque([root])\n    while q:\n        lv=[]\n        for _ in range(len(q)):\n            n=q.popleft();lv.append(n.val)\n            if n.left: q.append(n.left)\n            if n.right: q.append(n.right)\n        res.append(lv)\n    return res`,cpp:`vector<vector<int>> levelOrder(TreeNode* root){\n    vector<vector<int>> res;\n    if(!root)return res;\n    queue<TreeNode*> q;q.push(root);\n    while(!q.empty()){int sz=q.size();vector<int> lv;for(int i=0;i<sz;i++){auto n=q.front();q.pop();lv.push_back(n->val);if(n->left)q.push(n->left);if(n->right)q.push(n->right);}res.push_back(lv);}\n    return res;\n}`} },
  { slug: 'word-ladder', title: 'Word Ladder', difficulty: Difficulty.HARD, patternSlug: 'bfs', order: 2, companies: ['Amazon','Facebook','Google','LinkedIn'], tags: ['Hash Set','BFS','String'], description: 'Find shortest transformation sequence from beginWord to endWord, changing one letter at a time.\n\n**Example:**\nInput: beginWord="hit", endWord="cog", wordList=["hot","dot","dog","lot","log","cog"]\nOutput: 5', examples: [{input:'beginWord="hit",endWord="cog",wordList=["hot","dot","dog","lot","log","cog"]',output:'5'}], constraints:['1<=words.length<=5000'], hints:['BFS level by level','Try all single char changes at each step'], editorialText:'BFS. Each step try all 26 char substitutions.', editorialCode:{java:`public int ladderLength(String begin,String end,List<String> list){\n    Set<String> set=new HashSet<>(list);\n    Queue<String> q=new LinkedList<>();q.offer(begin);\n    int steps=1;\n    while(!q.isEmpty()){int sz=q.size();for(int i=0;i<sz;i++){String w=q.poll();if(w.equals(end))return steps;char[] arr=w.toCharArray();for(int j=0;j<arr.length;j++){char orig=arr[j];for(char c='a';c<='z';c++){arr[j]=c;String nw=new String(arr);if(set.contains(nw)){q.offer(nw);set.remove(nw);}arr[j]=orig;}}}\nsteps++;}\n    return 0;\n}`,python:`from collections import deque\ndef ladder_length(begin,end,word_list):\n    word_set=set(word_list)\n    q=deque([(begin,1)])\n    while q:\n        w,steps=q.popleft()\n        for i in range(len(w)):\n            for c in 'abcdefghijklmnopqrstuvwxyz':\n                nw=w[:i]+c+w[i+1:]\n                if nw==end: return steps+1\n                if nw in word_set: q.append((nw,steps+1));word_set.remove(nw)\n    return 0`,cpp:`int ladderLength(string b,string e,vector<string>& lst){\n    set<string> st(lst.begin(),lst.end());\n    queue<string> q;q.push(b);int steps=1;\n    while(!q.empty()){int sz=q.size();for(int i=0;i<sz;i++){string w=q.front();q.pop();if(w==e)return steps;for(int j=0;j<w.size();j++){char orig=w[j];for(char c='a';c<='z';c++){w[j]=c;if(st.count(w)){q.push(w);st.erase(w);}w[j]=orig;}}}\nsteps++;}\n    return 0;\n}`} },
  // DYNAMIC PROGRAMMING
  { slug: 'climbing-stairs', title: 'Climbing Stairs', difficulty: Difficulty.EASY, patternSlug: 'dynamic-programming', order: 1, companies: ['Amazon','Google','Adobe','Apple'], tags: ['Math','DP','Memoization'], description: 'Climb n stairs, 1 or 2 steps at a time. How many distinct ways?\n\n**Example:**\nInput: n=3\nOutput: 3\nExplanation: 1+1+1, 1+2, 2+1', examples: [{input:'n=2',output:'2'},{input:'n=3',output:'3'}], constraints:['1<=n<=45'], hints:['dp[i] = dp[i-1] + dp[i-2]','This is Fibonacci!'], editorialText:'Fibonacci DP. dp[i] = ways to reach stair i.', editorialCode:{java:`public int climbStairs(int n){\n    if(n<=2)return n;\n    int a=1,b=2;\n    for(int i=3;i<=n;i++){int c=a+b;a=b;b=c;}\n    return b;\n}`,python:`def climb_stairs(n):\n    if n<=2: return n\n    a,b=1,2\n    for _ in range(3,n+1): a,b=b,a+b\n    return b`,cpp:`int climbStairs(int n){\n    if(n<=2)return n;\n    int a=1,b=2;\n    for(int i=3;i<=n;i++){int c=a+b;a=b;b=c;}\n    return b;\n}`} },
  { slug: 'coin-change', title: 'Coin Change', difficulty: Difficulty.MEDIUM, patternSlug: 'dynamic-programming', order: 2, companies: ['Amazon','Google','Microsoft','Goldman Sachs'], tags: ['Array','DP','BFS'], description: 'Find fewest coins to make up amount. Return -1 if impossible.\n\n**Example:**\nInput: coins=[1,5,11], amount=15\nOutput: 3', examples: [{input:'coins=[1,2,5], amount=11',output:'3'},{input:'coins=[2], amount=3',output:'-1'}], constraints:['1<=coins.length<=12','0<=amount<=1e4'], hints:['dp[i] = min coins for amount i','dp[i] = min(dp[i-coin]+1) for each coin'], editorialText:'Bottom-up DP. dp[i] = min coins for amount i.', editorialCode:{java:`public int coinChange(int[] coins,int amount){\n    int[] dp=new int[amount+1];\n    Arrays.fill(dp,amount+1);\n    dp[0]=0;\n    for(int i=1;i<=amount;i++) for(int c:coins) if(c<=i) dp[i]=Math.min(dp[i],dp[i-c]+1);\n    return dp[amount]>amount?-1:dp[amount];\n}`,python:`def coin_change(coins,amount):\n    dp=[float('inf')]*(amount+1);dp[0]=0\n    for i in range(1,amount+1):\n        for c in coins:\n            if c<=i: dp[i]=min(dp[i],dp[i-c]+1)\n    return dp[amount] if dp[amount]!=float('inf') else -1`,cpp:`int coinChange(vector<int>& coins,int amount){\n    vector<int> dp(amount+1,amount+1);dp[0]=0;\n    for(int i=1;i<=amount;i++) for(int c:coins) if(c<=i) dp[i]=min(dp[i],dp[i-c]+1);\n    return dp[amount]>amount?-1:dp[amount];\n}`} },
  { slug: 'longest-increasing-subsequence', title: 'Longest Increasing Subsequence', difficulty: Difficulty.MEDIUM, patternSlug: 'dynamic-programming', order: 3, companies: ['Amazon','Microsoft','Google'], tags: ['Array','DP','Binary Search'], description: 'Find length of longest strictly increasing subsequence.\n\n**Example:**\nInput: nums=[10,9,2,5,3,7,101,18]\nOutput: 4\nExplanation: [2,3,7,101]', examples: [{input:'nums=[10,9,2,5,3,7,101,18]',output:'4'},{input:'nums=[0,1,0,3,2,3]',output:'4'}], constraints:['1<=nums.length<=2500'], hints:['dp[i] = LIS ending at index i','dp[i] = max(dp[j]+1) for all j<i where nums[j]<nums[i]'], editorialText:'DP O(n²). Or patience sorting for O(n log n).', editorialCode:{java:`public int lengthOfLIS(int[] nums){\n    int n=nums.length;\n    int[] dp=new int[n];\n    Arrays.fill(dp,1);\n    int max=1;\n    for(int i=1;i<n;i++){for(int j=0;j<i;j++) if(nums[j]<nums[i]) dp[i]=Math.max(dp[i],dp[j]+1);max=Math.max(max,dp[i]);}\n    return max;\n}`,python:`def length_of_lis(nums):\n    dp=[1]*len(nums)\n    for i in range(1,len(nums)):\n        for j in range(i):\n            if nums[j]<nums[i]: dp[i]=max(dp[i],dp[j]+1)\n    return max(dp)`,cpp:`int lengthOfLIS(vector<int>& n){\n    int sz=n.size(); vector<int> dp(sz,1); int mx=1;\n    for(int i=1;i<sz;i++){for(int j=0;j<i;j++) if(n[j]<n[i]) dp[i]=max(dp[i],dp[j]+1);mx=max(mx,dp[i]);}\n    return mx;\n}`} },
  { slug: 'house-robber', title: 'House Robber', difficulty: Difficulty.MEDIUM, patternSlug: 'dynamic-programming', order: 4, companies: ['Amazon','Google','Airbnb'], tags: ['Array','DP'], description: 'Rob houses without robbing adjacent ones. Find maximum amount.\n\n**Example:**\nInput: nums=[1,2,3,1]\nOutput: 4\nExplanation: Rob house 1 and 3 → 1+3=4', examples: [{input:'nums=[1,2,3,1]',output:'4'},{input:'nums=[2,7,9,3,1]',output:'12'}], constraints:['1<=nums.length<=100'], hints:['At each house: rob it (prev_prev+curr) or skip (prev)','dp[i] = max(dp[i-1], dp[i-2]+nums[i])'], editorialText:'dp[i] = max(dp[i-1], dp[i-2]+nums[i]). Optimize to O(1) space.', editorialCode:{java:`public int rob(int[] n){\n    if(n.length==1)return n[0];\n    int a=n[0],b=Math.max(n[0],n[1]);\n    for(int i=2;i<n.length;i++){int c=Math.max(b,a+n[i]);a=b;b=c;}\n    return b;\n}`,python:`def rob(nums):\n    if len(nums)==1: return nums[0]\n    a,b=nums[0],max(nums[0],nums[1])\n    for i in range(2,len(nums)):\n        a,b=b,max(b,a+nums[i])\n    return b`,cpp:`int rob(vector<int>& n){\n    if(n.size()==1)return n[0];\n    int a=n[0],b=max(n[0],n[1]);\n    for(int i=2;i<n.size();i++){int c=max(b,a+n[i]);a=b;b=c;}\n    return b;\n}`} },
  // BACKTRACKING
  { slug: 'subsets', title: 'Subsets', difficulty: Difficulty.MEDIUM, patternSlug: 'backtracking', order: 1, companies: ['Facebook','Amazon','Google'], tags: ['Array','Backtracking'], description: 'Return all possible subsets (power set) of unique integers.\n\n**Example:**\nInput: nums=[1,2,3]\nOutput: [[],[1],[2],[1,2],[3],[1,3],[2,3],[1,2,3]]', examples: [{input:'nums=[1,2,3]',output:'[[],[1],[2],[1,2],[3],[1,3],[2,3],[1,2,3]]'},{input:'nums=[0]',output:'[[],[0]]'}], constraints:['1<=nums.length<=10','All unique'], hints:['At each step: include or exclude current element','Add current state to results at every call'], editorialText:'Backtracking. Add copy of current to results at every call.', editorialCode:{java:`public List<List<Integer>> subsets(int[] nums){\n    List<List<Integer>> res=new ArrayList<>();\n    backtrack(res,new ArrayList<>(),nums,0);\n    return res;\n}\nvoid backtrack(List<List<Integer>> res,List<Integer> cur,int[] nums,int start){\n    res.add(new ArrayList<>(cur));\n    for(int i=start;i<nums.length;i++){cur.add(nums[i]);backtrack(res,cur,nums,i+1);cur.remove(cur.size()-1);}\n}`,python:`def subsets(nums):\n    res=[]\n    def bt(start,cur):\n        res.append(cur[:])\n        for i in range(start,len(nums)):\n            cur.append(nums[i]);bt(i+1,cur);cur.pop()\n    bt(0,[])\n    return res`,cpp:`vector<vector<int>> subsets(vector<int>& nums){\n    vector<vector<int>> res; vector<int> cur;\n    function<void(int)> bt=[&](int s){res.push_back(cur);for(int i=s;i<nums.size();i++){cur.push_back(nums[i]);bt(i+1);cur.pop_back();}};\n    bt(0); return res;\n}`} },
  { slug: 'permutations', title: 'Permutations', difficulty: Difficulty.MEDIUM, patternSlug: 'backtracking', order: 2, companies: ['Microsoft','Facebook','Amazon'], tags: ['Array','Backtracking'], description: 'Return all permutations of unique integers.\n\n**Example:**\nInput: nums=[1,2,3]\nOutput: [[1,2,3],[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]]', examples: [{input:'nums=[1,2,3]',output:'[[1,2,3],[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]]'}], constraints:['1<=nums.length<=6','All unique'], hints:['Swap nums[i] with nums[start] at each step'], editorialText:'Backtracking with swap approach or used[] array.', editorialCode:{java:`public List<List<Integer>> permute(int[] nums){\n    List<List<Integer>> res=new ArrayList<>();\n    bt(res,new ArrayList<>(),nums,new boolean[nums.length]);\n    return res;\n}\nvoid bt(List<List<Integer>> res,List<Integer> cur,int[] nums,boolean[] used){\n    if(cur.size()==nums.length){res.add(new ArrayList<>(cur));return;}\n    for(int i=0;i<nums.length;i++){if(used[i])continue;used[i]=true;cur.add(nums[i]);bt(res,cur,nums,used);cur.remove(cur.size()-1);used[i]=false;}\n}`,python:`def permute(nums):\n    res=[]\n    def bt(cur,remaining):\n        if not remaining: res.append(cur[:]);return\n        for i in range(len(remaining)):\n            cur.append(remaining[i])\n            bt(cur,remaining[:i]+remaining[i+1:])\n            cur.pop()\n    bt([],nums);return res`,cpp:`vector<vector<int>> permute(vector<int>& n){\n    vector<vector<int>> res;\n    sort(n.begin(),n.end());\n    do { res.push_back(n); } while(next_permutation(n.begin(),n.end()));\n    return res;\n}`} },
  // GREEDY
  { slug: 'jump-game', title: 'Jump Game', difficulty: Difficulty.MEDIUM, patternSlug: 'greedy', order: 1, companies: ['Amazon','Microsoft','Google'], tags: ['Array','Greedy','DP'], description: 'Given array where nums[i] is max jump length from index i, can you reach last index?\n\n**Example:**\nInput: nums=[2,3,1,1,4]\nOutput: true', examples: [{input:'nums=[2,3,1,1,4]',output:'true'},{input:'nums=[3,2,1,0,4]',output:'false'}], constraints:['1<=nums.length<=1e4'], hints:['Track maximum reachable index','If current index > maxReach, return false'], editorialText:'Greedy. Track maxReach. If i > maxReach, unreachable.', editorialCode:{java:`public boolean canJump(int[] nums){\n    int max=0;\n    for(int i=0;i<nums.length;i++){if(i>max)return false;max=Math.max(max,i+nums[i]);}\n    return true;\n}`,python:`def can_jump(nums):\n    max_reach=0\n    for i,v in enumerate(nums):\n        if i>max_reach: return False\n        max_reach=max(max_reach,i+v)\n    return True`,cpp:`bool canJump(vector<int>& n){\n    int mx=0;\n    for(int i=0;i<n.size();i++){if(i>mx)return false;mx=max(mx,i+n[i]);}\n    return true;\n}`} },
  { slug: 'meeting-rooms-ii', title: 'Meeting Rooms II', difficulty: Difficulty.MEDIUM, patternSlug: 'greedy', order: 2, companies: ['Facebook','Google','Amazon','Uber'], tags: ['Array','Greedy','Heap'], description: 'Find minimum number of conference rooms required for all meetings.\n\n**Example:**\nInput: intervals=[[0,30],[5,10],[15,20]]\nOutput: 2', examples: [{input:'intervals=[[0,30],[5,10],[15,20]]',output:'2'},{input:'intervals=[[7,10],[2,4]]',output:'1'}], constraints:['0<=intervals.length<=1e4'], hints:['Sort by start time','Use min-heap of end times','If earliest end <= current start, reuse room'], editorialText:'Sort by start. Min-heap tracks end times. If heap.peek() <= start, pop (reuse room).', editorialCode:{java:`public int minMeetingRooms(int[][] intervals){\n    Arrays.sort(intervals,(a,b)->a[0]-b[0]);\n    PriorityQueue<Integer> pq=new PriorityQueue<>();\n    for(int[] iv:intervals){if(!pq.isEmpty()&&pq.peek()<=iv[0])pq.poll();pq.offer(iv[1]);}\n    return pq.size();\n}`,python:`import heapq\ndef min_meeting_rooms(intervals):\n    intervals.sort();heap=[]\n    for s,e in intervals:\n        if heap and heap[0]<=s: heapq.heapreplace(heap,e)\n        else: heapq.heappush(heap,e)\n    return len(heap)`,cpp:`int minMeetingRooms(vector<vector<int>>& iv){\n    sort(iv.begin(),iv.end());\n    priority_queue<int,vector<int>,greater<int>> pq;\n    for(auto& i:iv){if(!pq.empty()&&pq.top()<=i[0])pq.pop();pq.push(i[1]);}\n    return pq.size();\n}`} },
  // HEAP
  { slug: 'top-k-frequent', title: 'Top K Frequent Elements', difficulty: Difficulty.MEDIUM, patternSlug: 'heap', order: 1, companies: ['Amazon','Facebook','Google'], tags: ['Array','Hash Map','Heap'], description: 'Return k most frequent elements.\n\n**Example:**\nInput: nums=[1,1,1,2,2,3], k=2\nOutput: [1,2]', examples: [{input:'nums=[1,1,1,2,2,3], k=2',output:'[1,2]'},{input:'nums=[1], k=1',output:'[1]'}], constraints:['1<=nums.length<=1e5','k is always valid'], hints:['Count frequencies','Min-heap of size k by frequency'], editorialText:'Hash map for freq. Min-heap of size k. O(n log k).', editorialCode:{java:`public int[] topKFrequent(int[] nums,int k){\n    Map<Integer,Integer> freq=new HashMap<>();\n    for(int n:nums)freq.merge(n,1,Integer::sum);\n    PriorityQueue<Integer> pq=new PriorityQueue<>((a,b)->freq.get(a)-freq.get(b));\n    for(int n:freq.keySet()){pq.offer(n);if(pq.size()>k)pq.poll();}\n    int[] res=new int[k];\n    for(int i=k-1;i>=0;i--)res[i]=pq.poll();\n    return res;\n}`,python:`import heapq\ndef top_k_frequent(nums,k):\n    freq={}\n    for n in nums: freq[n]=freq.get(n,0)+1\n    return heapq.nlargest(k,freq.keys(),key=freq.get)`,cpp:`vector<int> topKFrequent(vector<int>& nums,int k){\n    unordered_map<int,int> freq;\n    for(int n:nums)freq[n]++;\n    priority_queue<pair<int,int>,vector<pair<int,int>>,greater<>> pq;\n    for(auto& [n,f]:freq){pq.push({f,n});if(pq.size()>k)pq.pop();}\n    vector<int> res;\n    while(!pq.empty()){res.push_back(pq.top().second);pq.pop();}\n    return res;\n}`} },
  { slug: 'kth-largest-element', title: 'Kth Largest Element in Array', difficulty: Difficulty.MEDIUM, patternSlug: 'heap', order: 2, companies: ['Facebook','Amazon','Microsoft','Apple'], tags: ['Array','Heap','Quickselect'], description: 'Find kth largest element in unsorted array.\n\n**Example:**\nInput: nums=[3,2,1,5,6,4], k=2\nOutput: 5', examples: [{input:'nums=[3,2,1,5,6,4], k=2',output:'5'},{input:'nums=[3,2,3,1,2,4,5,5,6], k=4',output:'4'}], constraints:['1<=k<=nums.length<=1e4'], hints:['Min-heap of size k','Top of heap is kth largest'], editorialText:'Min-heap of size k. Root is kth largest.', editorialCode:{java:`public int findKthLargest(int[] nums,int k){\n    PriorityQueue<Integer> pq=new PriorityQueue<>();\n    for(int n:nums){pq.offer(n);if(pq.size()>k)pq.poll();}\n    return pq.peek();\n}`,python:`import heapq\ndef find_kth_largest(nums,k):\n    return heapq.nlargest(k,nums)[-1]`,cpp:`int findKthLargest(vector<int>& n,int k){\n    priority_queue<int,vector<int>,greater<>> pq;\n    for(int x:n){pq.push(x);if(pq.size()>k)pq.pop();}\n    return pq.top();\n}`} },
  // LINKED LIST
  { slug: 'reverse-linked-list', title: 'Reverse Linked List', difficulty: Difficulty.EASY, patternSlug: 'linked-list', order: 1, companies: ['Amazon','Microsoft','Adobe','Apple'], tags: ['Linked List','Recursion'], description: 'Reverse a singly linked list.\n\n**Example:**\nInput: head=[1,2,3,4,5]\nOutput: [5,4,3,2,1]', examples: [{input:'head=[1,2,3,4,5]',output:'[5,4,3,2,1]'},{input:'head=[1,2]',output:'[2,1]'}], constraints:['0<=nodes<=5000'], hints:['Track prev, curr, next','Redirect curr.next to prev'], editorialText:'Iterative: prev=null, redirect each node, advance.', editorialCode:{java:`public ListNode reverseList(ListNode head){\n    ListNode prev=null,curr=head;\n    while(curr!=null){ListNode next=curr.next;curr.next=prev;prev=curr;curr=next;}\n    return prev;\n}`,python:`def reverse_list(head):\n    prev,curr=None,head\n    while curr:\n        nxt=curr.next;curr.next=prev;prev,curr=curr,nxt\n    return prev`,cpp:`ListNode* reverseList(ListNode* h){\n    ListNode *p=nullptr,*c=h;\n    while(c){auto n=c->next;c->next=p;p=c;c=n;}\n    return p;\n}`} },
  { slug: 'linked-list-cycle', title: 'Linked List Cycle', difficulty: Difficulty.EASY, patternSlug: 'linked-list', order: 2, companies: ['Amazon','Microsoft','Bloomberg'], tags: ['Linked List','Two Pointers','Hash Table'], description: 'Detect if linked list has a cycle.\n\n**Example:**\nInput: head=[3,2,0,-4] with cycle at index 1\nOutput: true', examples: [{input:'head=[3,2,0,-4], pos=1',output:'true'},{input:'head=[1,2], pos=0',output:'true'},{input:'head=[1], pos=-1',output:'false'}], constraints:['0<=nodes<=1e4'], hints:['Floyd cycle detection: fast and slow pointers','If they meet, cycle exists'], editorialText:"Floyd's tortoise and hare.", editorialCode:{java:`public boolean hasCycle(ListNode head){\n    ListNode s=head,f=head;\n    while(f!=null&&f.next!=null){s=s.next;f=f.next.next;if(s==f)return true;}\n    return false;\n}`,python:`def has_cycle(head):\n    s=f=head\n    while f and f.next:\n        s=s.next;f=f.next.next\n        if s is f: return True\n    return False`,cpp:`bool hasCycle(ListNode* h){\n    ListNode *s=h,*f=h;\n    while(f&&f->next){s=s->next;f=f->next->next;if(s==f)return true;}\n    return false;\n}`} },
  { slug: 'merge-two-sorted-lists', title: 'Merge Two Sorted Lists', difficulty: Difficulty.EASY, patternSlug: 'linked-list', order: 3, companies: ['Amazon','Microsoft','Google','Adobe'], tags: ['Linked List','Recursion'], description: 'Merge two sorted linked lists into one sorted list.\n\n**Example:**\nInput: l1=[1,2,4], l2=[1,3,4]\nOutput: [1,1,2,3,4,4]', examples: [{input:'l1=[1,2,4], l2=[1,3,4]',output:'[1,1,2,3,4,4]'},{input:'l1=[], l2=[]',output:'[]'}], constraints:['0<=nodes<=50','-100<=val<=100'], hints:['Use dummy node','Compare heads, append smaller'], editorialText:'Dummy node. Iteratively attach smaller node.', editorialCode:{java:`public ListNode mergeTwoLists(ListNode l1,ListNode l2){\n    ListNode dummy=new ListNode(0),curr=dummy;\n    while(l1!=null&&l2!=null){if(l1.val<=l2.val){curr.next=l1;l1=l1.next;}else{curr.next=l2;l2=l2.next;}curr=curr.next;}\n    curr.next=l1!=null?l1:l2;\n    return dummy.next;\n}`,python:`def merge_two_lists(l1,l2):\n    dummy=curr=ListNode(0)\n    while l1 and l2:\n        if l1.val<=l2.val: curr.next=l1;l1=l1.next\n        else: curr.next=l2;l2=l2.next\n        curr=curr.next\n    curr.next=l1 or l2\n    return dummy.next`,cpp:`ListNode* mergeTwoLists(ListNode* l1,ListNode* l2){\n    ListNode dummy(0),*c=&dummy;\n    while(l1&&l2){if(l1->val<=l2->val){c->next=l1;l1=l1->next;}else{c->next=l2;l2=l2->next;}c=c->next;}\n    c->next=l1?l1:l2;\n    return dummy.next;\n}`} },
]

async function main() {
  console.log('🌱 Seeding database...')

  const hash = await bcrypt.hash('demo1234', 10)
  const user = await prisma.user.upsert({
    where: { email: 'demo@dsapatterns.dev' }, update: {},
    create: { email: 'demo@dsapatterns.dev', name: 'Demo User', password: hash, streak: 7, totalXP: 1240 }
  })
  console.log('✅ Demo user:', user.email)

  await prisma.user.upsert({
    where: { email: 'admin@dsapatterns.dev' }, update: {},
    create: { email: 'admin@dsapatterns.dev', name: 'Admin', password: hash, role: 'ADMIN', streak: 30, totalXP: 9999 }
  })

  const createdPatterns: Record<string, any> = {}
  for (const p of patterns) {
    const created = await prisma.pattern.upsert({ where: { slug: p.slug }, update: {}, create: p as any })
    createdPatterns[p.slug] = created
    console.log(`✅ Pattern: ${p.name}`)
  }

  for (const prob of problems) {
    const { patternSlug, ...data } = prob
    const pattern = createdPatterns[patternSlug]
    if (!pattern) { console.log(`⚠️ Pattern not found: ${patternSlug}`); continue }
    await prisma.problem.upsert({ where: { slug: prob.slug }, update: {}, create: { ...data, patternId: pattern.id } as any })
    console.log(`✅ Problem: ${prob.title}`)
  }

  for (const p of Object.values(createdPatterns)) {
    const totalCount = await prisma.problem.count({ where: { patternId: (p as any).id } })
    await prisma.userProgress.upsert({
      where: { userId_patternId: { userId: user.id, patternId: (p as any).id } }, update: {},
      create: { userId: user.id, patternId: (p as any).id, masteryLevel: Math.floor(Math.random()*70), solvedCount: Math.floor(Math.random()*3), totalCount, lastPracticed: new Date() }
    })
  }

  console.log('\n🎉 Done!')
  console.log('📧 demo@dsapatterns.dev / demo1234')
}

main().catch(console.error).finally(() => prisma.$disconnect())
